# Generated by Django 4.2.5 on 2023-09-30 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="img",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                default="", editable=False, max_length=250, unique=True
            ),
        ),
    ]
