# Generated by Django 4.2.5 on 2023-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_img_alter_blog_body_alter_blog_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
    ]
