# Generated by Django 4.2.5 on 2023-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="pin",
            field=models.CharField(
                choices=[("PI", "Pin"), ("UN", "Unpin")], default="UN", max_length=2
            ),
        ),
    ]
